# PyTorch Nightly PyTorch Tests Builds Pipeline on Azure DevOps
#
# This pipeline runs custom PyTorch unit-tests on nightly
# PyTorch wheels.

stages:
- stage: 'NightlyCustomTests'
  displayName: 'Run custom unit tests on PyTorch wheels'
  jobs:
  - template: job_templates/pytorch-template-unix.yml
    parameters:
      name: ubuntu_1804_CPU_docker
      pool: 'PyTorch-Linux-CPU'
      container_endpoint: pytorchms.azurecr.io
      customMatrixes:
        Py_37:
          container_image: pytorchms.azurecr.io/ubuntu_1804_cpu_dev
          PYTHON_VERSION: 3.7
          CUDA_VERSION: cpu
          RUN_TESTS: $(RUN_TESTS_LIN)
          NIGHTLY_BUILD: True
