# Initiate 5 agentless-server waiting jobs to check on the
# status of PR artifact builds, for a maximum wait time of
# 8*60 min=480 mins. These jobs will pass immediately
# once targeted CircleCI build is ready.

jobs:
# Ensure that ample time is afforded to the PR CircleCI builds to start
# building artifacts.
- job: Delay5MinForCircleCI
  pool: server
  steps:
  - task: Delay@1
    inputs:
      delayForMinutes: '5'

- job: checkjob1
  pool: server
  timeoutInMinutes: 60
  dependsOn: Delay5MinForCircleCI
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob2
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob1
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob3
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob2
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob4
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob3
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob5
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob4
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob6
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob5
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob7
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob6
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml

- job: checkjob8
  pool: server
  timeoutInMinutes: 60
  dependsOn: checkjob7
  continueOnError: true
  steps:
  - template: wheel-wait-job-template.yml
